- name: Display list of files in /var/log
  hosts: vpn
  become: yes

  tasks:
    - name: list logs
      ansible.builtin.command: ls /var/log
      register: log_files
    - name: Output list of log files
      ansible.builtin.debug:
        var: log_files.stdout_lines